package protocol

const (
	CLIENT_VERSION_NUMBER = 134729835

	ACCOUNTLEN     = 30
	MAPNAMELEN     = 16
	ACTORNAMELEN   = 14
	MAXBAGITEM     = 46
	MAXHEROBAGITEM = 40
	MAXMAGIC       = 30
	MAXSTORAGEITEM = 50

	DEFBLOCKSIZE = 16
	BUFFERSIZE   = 12000
	DATA_BUFSIZE2 = 16348
	DATA_BUFSIZE  = 8192

	GROUPMAX = 11
	BAGGOLD  = 5000000

	MAX_STATUS_ATTRIBUTE = 12
)

const (
	DR_UP       = 0
	DR_UPRIGHT  = 1
	DR_RIGHT    = 2
	DR_DOWNRIGHT = 3
	DR_DOWN     = 4
	DR_DOWNLEFT = 5
	DR_LEFT     = 6
	DR_UPLEFT   = 7
)

const (
	AT_FIRE     = 1
	AT_ICE      = 2
	AT_LIGHT    = 3
	AT_WIND     = 4
	AT_HOLY     = 5
	AT_DARK     = 6
	AT_PHANTOM  = 7
)

const (
	U_DRESS     = 0
	U_WEAPON    = 1
	U_RIGHTHAND = 2
	U_NECKLACE  = 3
	U_HELMET    = 4
	U_ARMRINGL  = 5
	U_ARMRINGR  = 6
	U_RINGL     = 7
	U_RINGR     = 8
	U_BUJUK     = 9
	U_BELT      = 10
	U_BOOTS     = 11
	U_CHARM     = 12
)

const (
	POISON_DECHEALTH  = 0
	POISON_DAMAGEARMOR = 1
	POISON_FREEZE     = 2
	POISON_LOCKSPELL  = 3
	POISON_DONTMOVE   = 4
	POISON_STONE      = 5
	POISON_SLOWDOWN   = 6
)

const (
	STATE_RAGEDEMEGEUP       = 7
	STATE_TRANSPARENT        = 8
	STATE_DEFENCEUP          = 9
	STATE_MAGDEFENCEUP       = 10
	STATE_BUBBLEDEFENCEUP    = 11
	STATE_PROTECTIONFIELDDUP = 12
	POISON_BLIND             = 13
	POISON_CHAOS             = 14
	STATE_MAGICBOOSTERUP     = 15
)

const (
	RC_PLAYOBJECT  = 0
	RC_DUMMOBJECT  = 1
	RC_MOONOBJECT  = 60
	RC_HEROOBJECT  = 66
	RC_PEACENPC    = 15
	RC_ANIMAL      = 50
	RC_MONSTER     = 80
	RC_NPC         = 10
	RC_GUARD       = 11
	RC_ARCHERGUARD = 112
	RC_PLAYMOSTER  = 150
)

const (
	USERMODE_PLAYGAME = 1
	USERMODE_LOGIN    = 2
	USERMODE_LOGOFF   = 3
	USERMODE_NOTICE   = 4
)

const (
	RUNGATEMAX    = 20
	RUNGATECODE   = 0xAA55AA55
	ISM_WHISPER   = 1234
)

const (
	OS_MOVINGOBJECT = 1
	OS_ITEMOBJECT   = 2
	OS_EVENTOBJECT  = 3
	OS_GATEOBJECT   = 4
	OS_SWITCHOBJECT = 5
	OS_MAPEVENT     = 6
	OS_DOOR         = 7
	OS_ROON         = 8
	OS_OBJECTGATE   = 9
)

const (
	ET_TRAP         = 0
	ET_DIGOUTZOMBI  = 1
	ET_PILESTONES   = 3
	ET_HOLYCURTAIN  = 4
	ET_FIRE         = 5
	ET_SCULPEICE    = 6
	ET_WEB          = 7
	ET_FIREFLOWER_1 = 8
	ET_FIREFLOWER_2 = 9
	ET_FIREFLOWER_3 = 10
	ET_FIREFLOWER_4 = 11
	ET_FIREFLOWER_5 = 12
	ET_FIREFLOWER_6 = 13
	ET_FIREFLOWER_7 = 14
	ET_FIREFLOWER_8 = 15
	ET_MAGICLOCK    = 16
	ET_MAPMAGIC     = 17
	ET_SPACEDOOR_1  = 18
	ET_SPACEDOOR_2  = 19
	ET_SPACEDOOR_3  = 20
	ET_SPACEDOOR_4  = 21
	ET_SPACEDOOR_5  = 22
	ET_SPACEDOOR_6  = 23
)
